### ISSUE TITLE
Can you publish version 1.0.2?

### ISSUE THREAD

**Issue by Briscoooe** [merge-api/merge-hris-python#28]
I notice the latest master branch code is [marked as version 1.0.2](https://github.com/merge-api/merge-hris-python/blob/master/setup.py#L15) but the [latest pypi version is 1.0.0](https://pypi.org/project/merge-hris-client/). Is there a reason this has not been published to pypi?

I ask as I am running into an issue generating an AccountToken. The AccountToken model in version 1.0.0 (the package on pypi) is missing the `integration` property that exists in the lastest master version (1.0.2). The absence of this property causes this error when trying to generate account tokens:

```AccountToken has no attribute 'integration' at ['received_data']['integration']```

When I checkout the latest master branch of this repo, it works fine as the issue has already been fixed. [This commit](https://github.com/merge-api/merge-hris-python/commit/003ff7dd1cc870b11a5f70fef8ee4888fa920518/MergeHRISClient/model/account_token.py) contains the fix. Specifically, the addition of the `integrations` property on line 84:

``` class AccountToken(ModelNormal):
     """NOTE: This class is auto generated by OpenAPI Generator.
@@ -74,8 +78,10 @@ class AccountToken(ModelNormal):
             openapi_types (dict): The key is attribute name
                 and the value is attribute type.
         """
+        lazy_import()
         return {
             'account_token': (str,),  # noqa: E501
+            'integration': (AccountIntegration,),  # noqa: E501
         }

```

This commit was made June 9, last publish date on Pypi was May 10.

I know I could fork this repo and use that version in my app but I would prefer to use the official version. Do you guys plan to publish this? Let me know, thanks

**Comment by io-ma** [comment]
I found 1.0.2 here is this the same thing? [Merge HRIS Client](https://pypi.org/project/MergeHRISClient/)
There are two for ats and 2 for HRIS:[dan-merge](https://pypi.org/user/dan-merge/)

**Comment by one-purpose-io** [comment]
Interesting. Can @dan-merge or @gilfeig confirm what the correct Pypi package is going forward?

**Comment by Briscoooe** [comment]
Interesting. Can @dan-merge or @gilfeig confirm what the correct Pypi package is going forward?

**Comment by dan-merge** [comment]
Hi @Briscoooe, I just pushed the most recent version to merge-hris-client. Out apologies, you should be able to use this SDK moving forwards!

**Comment by Briscoooe** [comment]
great, thanks!

**Comment by io-ma** [comment]
Thank you!
